site:
  title: Neo4j Labs Docs
  url: /labs/docs

content:
  sources:
  - url: https://github.com/neo4j-contrib/neo4j-helm.git
    branches: ['master']
    start_path: doc/docs
  - url: https://github.com/neo4j-contrib/neo4j-apoc-procedures
    branches: ['4.1', '4.0']
    start_path: docs/asciidoc
  - url: https://github.com/neo4j-labs/neosemantics
    branches: ['4.0']
    start_path: docs
  # - url: https://github.com/neo-technology/neo4j-etl
  #   branches: ['4.0']
  #   start_path: neo4j-etl-docs

output:
  dir: ./build/site/labs/
ui:
  bundle:
    url: ui/build/ui-bundle.zip
    snapshot: true
urls:
  html_extension_style: indexify
asciidoc:
  extensions:
  - ./extensions/remote-include/remote-include-processor
  - ./extensions/macros/macros
  attributes:
    page-theme: labs
